"""Canonical inventory of systems. Each entry says what it is and what it is not."""

from __future__ import annotations

from app.models import SourceDef

SOURCES: list[SourceDef] = [
    SourceDef(
        id="ourairports",
        name="OurAirports",
        layer="reference",
        role="Nightly public-domain dumps: countries.csv, regions.csv, airports.csv, runways.csv, navaids.csv. This is the aviation gazetteer, not a shop.",
        is_not="Not a timetable, fare, booking, or live track. Country codes here are ISO 3166-1 alpha-2 as used on airport rows.",
        freshness="Regenerated nightly; public domain.",
        url="https://ourairports.com/data/",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="geonames-countries",
        name="GeoNames countryInfo",
        layer="reference",
        role="ISO2/ISO3, capital, currency, population, languages, phone, TLD. Joined to OurAirports countries on ISO 3166-1 alpha-2.",
        is_not="Not an airport database. CC BY attribution to GeoNames.",
        freshness="Downloadable dump from download.geonames.org.",
        url="https://download.geonames.org/export/dump/",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="openflights-routes",
        name="OpenFlights routes",
        layer="historical-route-map",
        role="Which airlines historically published a nonstop between two IATA codes.",
        is_not="Not current schedules, not inventory, not a price. Last material dump ~2014–2017.",
        freshness="Frozen / stale. Use only as a structural prior for C-candidate generation.",
        url="https://openflights.org/data.php",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="opensky",
        name="OpenSky Network",
        layer="live-track",
        role="ADS-B / MLAT / ASTERIX / FLARM state vectors: who is in the air right now near an airport.",
        is_not="Not a ticket, not a fare, not a future schedule. Coverage has gaps (oceans, sparse receivers). Anonymous access is current states only, ~10s resolution.",
        freshness="Live (seconds). Historical arrivals/departures need an OpenSky account.",
        url="https://opensky-network.org",
        can_price=False,
        can_book=False,
        can_track=True,
    ),
    SourceDef(
        id="flightradar24",
        name="Flightradar24",
        layer="live-track-link",
        role="Commercial tracker (ADS-B + MLAT + radar + FAA). We deep-link; we do not scrape or resell their feed.",
        is_not="Not a booker. A position on FR24 is not a reservation.",
        freshness="Live on their site.",
        url="https://www.flightradar24.com",
        can_price=False,
        can_book=False,
        can_track=True,
    ),
    SourceDef(
        id="flightaware",
        name="FlightAware",
        layer="live-track-link",
        role="Commercial tracker / status (FAA SWIM + ADS-B). Deep-link only.",
        is_not="Not a booker. AeroAPI (paid) would be a status API; this app does not call it unless you add a key later.",
        freshness="Live on their site.",
        url="https://www.flightaware.com",
        can_price=False,
        can_book=False,
        can_track=True,
    ),
    SourceDef(
        id="aerodatabox",
        name="AeroDataBox FIDS",
        layer="schedule-status",
        role="Airport flight-information board: scheduled / estimated / actual departures and arrivals.",
        is_not="Not a fare shop and not ADS-B tracking (unless withLocation). Requires a RapidAPI key.",
        freshness="Operational board, typically hours around now — not a 330-day timetable.",
        url="https://aerodatabox.com",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="amadeus",
        name="Amadeus Self-Service",
        layer="priced-offer",
        role="GDS shopping: Flight Offers Search returns priced itineraries (fare + tax + RBD). Flight Offers Price confirms. Flight Create Orders would create a PNR — this app does not call Create Orders.",
        is_not="Not ADS-B. Test hostname is not production inventory. A search offer is not a ticket.",
        freshness="Live shop if AMADEUS_CLIENT_ID/SECRET are set.",
        url="https://developers.amadeus.com",
        can_price=True,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="duffel",
        name="Duffel",
        layer="priced-offer",
        role="Airline-retailing aggregator (NDC + other). Offer Request = shop. Order = book. This app shops only; it never creates an order or takes payment.",
        is_not="Test tokens return Duffel Airways sandbox offers, which are not real tickets.",
        freshness="Live shop if DUFFEL_TOKEN is set.",
        url="https://duffel.com/docs",
        can_price=True,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="google-flights",
        name="Google Flights",
        layer="meta-search",
        role="Metasearch. Compares airline/OTA prices and hands you off. Deep-link only.",
        is_not="Does not issue the e-ticket. Not a GDS you query from this API.",
        freshness="Live on Google when you click through.",
        url="https://www.google.com/travel/flights",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="kayak",
        name="Kayak",
        layer="meta-search",
        role="Metasearch / comparison. Deep-link only.",
        is_not="Usually not the validating carrier. The booking happens on an airline or OTA.",
        freshness="Live on Kayak when you click through.",
        url="https://www.kayak.com",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="skyscanner",
        name="Skyscanner",
        layer="meta-search",
        role="Metasearch. Deep-link only.",
        is_not="Not the ticket issuer.",
        freshness="Live on Skyscanner when you click through.",
        url="https://www.skyscanner.com",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="momondo",
        name="Momondo",
        layer="meta-search",
        role="Kayak-family metasearch. Deep-link only.",
        is_not="Not the ticket issuer.",
        freshness="Live on Momondo when you click through.",
        url="https://www.momondo.com",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="cheapflights",
        name="Cheapflights",
        layer="meta-search",
        role="Kayak-family metasearch. Deep-link only.",
        is_not="Not the ticket issuer.",
        freshness="Live on Cheapflights when you click through.",
        url="https://www.cheapflights.com",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="wego",
        name="Wego",
        layer="meta-search",
        role="Metasearch for Middle East and Asia. Deep-link only.",
        is_not="Not the ticket issuer.",
        freshness="Live on Wego when you click through.",
        url="https://www.wego.com",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
    SourceDef(
        id="expedia",
        name="Expedia",
        layer="ota",
        role="Online travel agency. Typically issues via GDS as merchant of record.",
        is_not="Not airline-direct NDC (except where Expedia has NDC contracts). Deep-link only.",
        freshness="Live on Expedia when you click through.",
        url="https://www.expedia.com",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="booking-com",
        name="Booking.com",
        layer="ota",
        role="OTA flight shop. Deep-link only — we open their one-way search, we do not book.",
        is_not="Not a fare we price in this API. Checkout happens on Booking.com.",
        freshness="Live on Booking.com when you click through.",
        url="https://flights.booking.com",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="trip-com",
        name="Trip.com",
        layer="ota",
        role="OTA flight shop. Deep-link only — we open their one-way search, we do not book.",
        is_not="Not a fare we price in this API. Checkout happens on Trip.com.",
        freshness="Live on Trip.com when you click through.",
        url="https://www.trip.com/flights",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="priceline",
        name="Priceline",
        layer="ota",
        role="OTA. Deep-link only.",
        is_not="Not a fare we price in this API.",
        freshness="Live on Priceline when you click through.",
        url="https://www.priceline.com",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="kiwi",
        name="Kiwi.com",
        layer="ota",
        role="OTA and virtual-interline shop. Deep-link only.",
        is_not="Self-transfer is not a hidden-city inversion. We do not book.",
        freshness="Live on Kiwi when you click through.",
        url="https://www.kiwi.com",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="cheapoair",
        name="CheapOair",
        layer="ota",
        role="US OTA. Deep-link only.",
        is_not="Not a fare we price in this API.",
        freshness="Live on CheapOair when you click through.",
        url="https://www.cheapoair.com",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="edreams",
        name="eDreams",
        layer="ota",
        role="European OTA. Deep-link only.",
        is_not="Not a fare we price in this API.",
        freshness="Live on eDreams when you click through.",
        url="https://www.edreams.com",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="traveloka",
        name="Traveloka",
        layer="ota",
        role="Southeast Asia OTA. Deep-link only.",
        is_not="Not a fare we price in this API.",
        freshness="Live on Traveloka when you click through.",
        url="https://www.traveloka.com",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="makemytrip",
        name="MakeMyTrip",
        layer="ota",
        role="India OTA. Deep-link only.",
        is_not="Not a fare we price in this API.",
        freshness="Live on MakeMyTrip when you click through.",
        url="https://www.makemytrip.com",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="despegar",
        name="Despegar",
        layer="ota",
        role="Latin America OTA. Deep-link only.",
        is_not="Not a fare we price in this API.",
        freshness="Live on Despegar when you click through.",
        url="https://www.despegar.com",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="airline-direct",
        name="Airline.com",
        layer="airline-direct",
        role="Carrier website / NDC. The airline is usually merchant of record.",
        is_not="A deep link is a search, not a confirmed PNR.",
        freshness="Live on the carrier site.",
        url="https://www.iata.org/en/programs/airline-distribution/ndc/",
        can_price=False,
        can_book=True,
        can_track=False,
    ),
    SourceDef(
        id="skiplagged-com",
        name="Skiplagged.com",
        layer="specialist-meta",
        role="Consumer hidden-city search product. Deep-link for comparison.",
        is_not="This repository is not Skiplagged. Linking is not an endorsement or a booking.",
        freshness="Live on their site.",
        url="https://skiplagged.com",
        can_price=False,
        can_book=False,
        can_track=False,
    ),
]


def sources_payload(enabled: dict[str, bool]) -> list[dict]:
    out = []
    for s in SOURCES:
        item = s.model_dump()
        item["configured"] = enabled.get(
            s.id,
            s.id in {"ourairports", "geonames-countries", "openflights-routes"}
            or s.layer.endswith("link")
            or s.layer in {"meta-search", "ota", "airline-direct", "specialist-meta", "live-track-link"},
        )
        if s.id == "opensky":
            item["configured"] = True
        if s.id == "amadeus":
            item["configured"] = enabled.get("amadeus", False)
        if s.id == "duffel":
            item["configured"] = enabled.get("duffel", False)
        if s.id == "aerodatabox":
            item["configured"] = enabled.get("aerodatabox", False)
        out.append(item)
    return out
